server.port=${PORT:5000}

fanta.filePath=C:\\app\\Calendario_Fantacalcio-di-Via-Adda-XXXV-edizione.xlsx
fanta.players=12
fanta.home-advantage=2
fanta.permutation-limit=5000
# 1 = single-thread | -1 = auto (availableProcessors) | N = fixed pool
fanta.threads=-1
